# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Users:
            algorithm: bcrypt
            cost: 10

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        doctrine:
            entity:
                class: AppBundle:Users
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: doctrine
            form_login:
                check_path: /api/login_check
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api_products:
            pattern:   ^/api/products
            stateless: true
            provider: doctrine
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        api_users:
            pattern:   ^/api/users
            stateless: true
            provider: doctrine
            methods: [GET,PUT,PATCH,DELETE]
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        #- { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api/users, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
