# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter: value
    acme_api.event.jwt_response_listener.class: AppBundle\EventListener\JWTResponseListener

services:
    crv.doctrine_entity_repository.products:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Products

    crv.doctrine_entity_repository.users:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Users

    app.event.jwt_response_listener:
        class: %acme_api.event.jwt_response_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }